name: CI/CD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python for Backend
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Backend Tests
        run: |
          cd backend
          pytest

      # Setup Node.js for Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test

      # Deploy Backend
      - name: Deploy Backend to Railway
        run: curl -X POST https://api.railway.app/deploy-webhook/YOUR_BACKEND_HOOK

      # Deploy Frontend
      - name: Deploy Frontend to Vercel
        run: vercel --prod
